services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://auth_db:5432/${DB_NAME}
      KC_DB_USERNAME: ${DB_USERNAME}
      KC_DB_PASSWORD: ${DB_PASSWORD}

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true

      KEYCLOAK_ADMIN: ${ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      
    command: start-dev
    depends_on:
      - auth_db
    ports:
      - 8080:8080

  auth_db:
    image: postgres:latest
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - auth_db_data:/var/lib/postgresql/data

volumes:
  auth_db_data:
